### ISSUE TITLE
Add current version number.

### ISSUE THREAD

**Issue by rhys-vdw** [rhys-vdw/minami#1]
As requested in tgriesser/bookshelf#895 by @rauls.

> ...could you add the version number to the top of the page, and left menu and page title too?

**Comment by ricardograca** [comment]
Fixed in bookshelf/bookshelf@f4dd79267ad8267a7073dd5c9f0661f6591ae96f. It's just a version badge next to the other badges, but it's enough for now. If we ever start generating docs for several different versions of Bookshelf at the same time it may be necessary to add the version number to all the places suggested here.

Will be released shortly.
